"""add users table

Revision ID: 89a8ca66c82b
Revises: 27192f00d59d
Create Date: 2025-05-10 21:23:53.903951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a8ca66c82b'
down_revision = '27192f00d59d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###